FROM arm64v8/python:3.7.2-alpine

COPY qemu-armx64-static /usr/bin/qemu-arm-static

ENV TZ UTC

WORKDIR /app

COPY /requirements.txt /setup.py /entrypoint /README.md /app/

RUN apk add --no-cache tzdata && \
    pip install --no-cache-dir -r requirements.txt

COPY /docupdater /app/docupdater

RUN pip install --no-cache-dir .

ENTRYPOINT ["entrypoint"]